const BAD_REQUEST = 400;
const UNAUTHORIZED = 401;
const FORBIDDEN = 403;
const NOT_FOUND = 404;
const INTERNAL_SERVER_ERROR = 500;
const JWT_SALT = "q7jb40keq1";

const INT_SERV_ERR_MESSAGE = "На сервере произошла ошибка";

module.exports = {
  BAD_REQUEST,
  UNAUTHORIZED,
  FORBIDDEN,
  NOT_FOUND,
  INTERNAL_SERVER_ERROR,
  INT_SERV_ERR_MESSAGE,
  JWT_SALT,
};
